### ISSUE TITLE
pylint is unable to import murl

### ISSUE THREAD

**Issue by rkonda** [berkerpeksag/murl#15]
Possibly because **init**.py is not in this package?

**Comment by berkerpeksag** [comment]
Thanks for the report, @rkonda. The murl module is consist of a `murl.py` Python file. `murl.py` is also marked as a Python module instead of a Python package at https://github.com/berkerpeksag/murl/blob/master/setup.py#L30. So this means there is no need a `__init__py`. Could you please give more details about this? What is the actual traceback? Which Python version are you using?

**Comment by rkonda** [comment]
It's probably this issue:
http://stackoverflow.com/questions/9602811/how-to-tell-pylint-to-ignore-certain-imports
http://docs.pylint.org/faq.html says that pylint doesn't import live
modules.

python 2.7.9

This is all I see from pylint

  9, 0: [F0401] Unable to import 'murl'

I guess murl can be added to path when running pylint. Is there a better
solution?

Rajesh

**Comment by berkerpeksag** [comment]
Well, I wouldn't recommend to let pylint check all third party packages. I think ignoring those paths would be the best action: http://docs.pylint.org/run.html#command-line-options

**Comment by berkerpeksag** [comment]
According to http://stackoverflow.com/a/39348054, a solution is available since pylint 0.10:

``` py
import murl  # pylint: disable=import-error
```
